const defaults=[
{id:1,name:'Cimus',ripen:'Ultra rana',color:'Bijela',desc:'Veoma rana stona sorta privlačnog izgleda i prijatnog ukusa.',exp:'Prve bobice moguće je konzumirati već od 1. avgusta.',sp:12,sq:8,cp:4,cq:25},
{id:2,name:'Katalonija',ripen:'Ultra rana',color:'Crna',desc:'Rana tamna stona sorta krupnih bobica i upečatljivih grozdova.',exp:'Kod mene sazrijeva oko 10. avgusta i pokazala se dobro.',sp:15,sq:0,cp:5,cq:12},
{id:3,name:'Preobraženje',ripen:'Rana',color:'Crvena',desc:'Atraktivna stona sorta sa krupnim izduženim bobicama i velikim grozdovima.',exp:'Sazrijeva oko 20. avgusta. Najbolje rezultate daje uz dužu rezidbu.',sp:15,sq:7,cp:5,cq:18},
{id:4,name:'Viktor',ripen:'Rana',color:'Crvena',desc:'Krupna i ukusna stona sorta ranog perioda zrenja.',exp:'Na mom terenu sazrijeva od 15. do 30. avgusta i pokazala se pouzdano.',sp:15,sq:11,cp:5,cq:0},
{id:5,name:'Kameleon',ripen:'Rana',color:'Crvena',desc:'Snažna stona sorta lijepih krupnih grozdova i skladnog ukusa.',exp:'Sazrijeva od 10. do 20. avgusta. Stabilna je i otporna.',sp:14,sq:4,cp:4,cq:17},
{id:6,name:'Helios',ripen:'Rana',color:'Crvena',desc:'Stona sorta čvršće bobice, lijepog ukusa i atraktivnog izgleda.',exp:'Kod mene sazrijeva od 20. do 30. avgusta.',sp:14,sq:0,cp:4,cq:9},
{id:7,name:'Gala',ripen:'Srednje rana',color:'Crna',desc:'Rodna i otporna stona sorta ujednačenih tamnih grozdova.',exp:'Sazrijeva od 20. do 30. avgusta. Ukus je jednostavan, a rod stabilan.',sp:13,sq:6,cp:4,cq:20},
{id:8,name:'Garmonia',ripen:'Srednje rana',color:'Crna',desc:'Ukusna, snažna i laka za uzgoj, pogodna i za manje vinograde.',exp:'Kod mene sazrijeva oko 30. avgusta i pokazala se veoma dobro.',sp:15,sq:9,cp:5,cq:15},
{id:9,name:'Sfinks',ripen:'Srednje rana',color:'Crna',desc:'Rana tamna sorta snažnog rasta i dobre otpornosti na bolesti.',exp:'Sazrijeva od 15. do 30. avgusta. Poslije obilne kiše može doći do pucanja bobica.',sp:13,sq:3,cp:4,cq:0},
{id:10,name:'Bajkonur',ripen:'Srednje rana',color:'Crna',desc:'Atraktivna stona sorta izduženih tamnih bobica i prijatnog ukusa.',exp:'Na mom terenu sazrijeva oko 5. septembra i pokazala se dobro.',sp:11,sq:5,cp:4,cq:12},
{id:11,name:'Bijela mirisavka',ripen:'Kasna',color:'Bijela',desc:'Mirisava bijela sorta slatkih bobica i dobre otpornosti.',exp:'Kod mene sazrijeva oko 20. septembra.',sp:12,sq:0,cp:4,cq:14},
{id:12,name:'Zarevo',ripen:'Kasna',color:'Crvena',desc:'Kasna stona sorta prepoznatljiva po krupnim crvenkastim grozdovima.',exp:'Zahtijeva dužu i topliju jesen kako bi potpuno sazrela.',sp:14,sq:4,cp:4,cq:8}
];
const current=(JSON.parse(localStorage.getItem('vp-varieties')||'null')||defaults).map(v=>({...v,name:['Ratatuji','Ratatui'].includes(v.name)?'Ratatuj':v.name,ripen:v.ripen==='Srednje kasna'?'Kasna':v.ripen})),master=window.fullCatalog||[];let varieties=[...master.map(v=>{const old=current.find(x=>x.id===v.id)||current.find(x=>x.name.toLowerCase()===v.name.toLowerCase());if(!old)return v;if(v.revision&&v.revision!==old.revision)return{...old,...v,sq:old.sq,cq:old.cq,featured:old.featured};return{...v,...old,type:old.type||v.type,images:old.images?.length?old.images:v.images}}),...current.filter(x=>!master.some(v=>v.id===x.id||v.name.toLowerCase()===x.name.toLowerCase()))],cart=[],pendingImages=[];varieties=varieties.map((v,i)=>({...v,type:v.type||'Stona',featured:v.featured===undefined?i<6:Boolean(v.featured)}));localStorage.setItem('vp-varieties',JSON.stringify(varieties));const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
varieties=varieties.filter(v=>v.name!=='Baikonur');
const knownDisadvantages={
'Arkadia':'Osjetljivost na pepelnicu i sivu trulež. Zahtijeva dobru regulaciju prinosa jer preopterećenje smanjuje kvalitet bobica. U hladnim godinama može slabije nakupljati šećer.',
'Sfinks':'Poslije obilne kiše može doći do pucanja bobica; potrebna je preventivna zaštita.',
'Kodrjanka':'Sklona je zametanju sitnih bobica, a u nepovoljnim uslovima može se javiti trulež.',
'Zarevo':'Zahtijeva dužu i topliju jesen kako bi potpuno sazrela.',
'Livija':'Srednja otpornost na bolesti; potrebna je redovna preventivna zaštita.',
'Artek':'Posebno treba paziti na oidijum i provoditi preventivnu zaštitu.'
};
varieties=varieties.map(v=>({...v,disadvantages:v.disadvantages||knownDisadvantages[v.name]||''}));
const ripeningOrder={'Ultra rana':1,'Rana':2,'Srednje rana':3,'Kasna':4,'Za provjeru':6},colorOrder={'Bijela':1,'Crvena':2,'Crna':3,'Za provjeru':4};varieties.sort((a,b)=>(ripeningOrder[a.ripen]||9)-(ripeningOrder[b.ripen]||9)||(colorOrder[a.color]||9)-(colorOrder[b.color]||9)||a.name.localeCompare(b.name,'sr'));
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="purchase.css">');
function save(){localStorage.setItem('vp-varieties',JSON.stringify(varieties))}function money(n){return Number(n||0).toFixed(2).replace('.',',')+' KM'}
function art(v){return v.images?.length?`<button type="button" class="grape-art photo art-link" onclick="detail(${v.id})" aria-label="Otvori detalje sorte ${v.name}"><img src="${v.images[0]}" alt="Grožđe sorte ${v.name}" loading="lazy"></button>`:`<button type="button" class="grape-art art-link ${v.color==='Crna'?'dark':v.color==='Crvena'?'red':''}" onclick="detail(${v.id})" aria-label="Otvori detalje sorte ${v.name}">🍇</button>`}function card(v){return `<article class="card">${art(v)}<div class="card-body"><span class="tag">${v.ripen} · ${v.color}</span><h3><button type="button" class="name-link" onclick="detail(${v.id})">${v.name}</button></h3><p>${v.desc}</p><div class="stock-row"><div class="stock ${!v.sq?'none':''}">Sadnica<b>${v.sq?money(v.sp):'Nema na stanju'}</b><small>Raspoloživo: ${v.sq}</small></div><div class="stock ${!v.cq?'none':''}">Reznica<b>${v.cq?money(v.cp):'Nema na stanju'}</b><small>Raspoloživo: ${v.cq}</small></div></div><details id="picker-${v.id}" class="custom-select"><summary id="picker-label-${v.id}">Izaberite sadnicu ili reznicu <span>⌄</span></summary><div class="kind-options"><button type="button" data-product-id="${v.id}" data-product-type="Reznica" onclick="event.preventDefault();event.stopPropagation();chooseProduct(this,${v.id},'Reznica')" ${!v.cq?'disabled':''}>Reznica <b>${v.cq?money(v.cp):'Nema na stanju'}</b></button><button type="button" data-product-id="${v.id}" data-product-type="Sadnica" onclick="event.preventDefault();event.stopPropagation();chooseProduct(this,${v.id},'Sadnica')" ${!v.sq?'disabled':''}>Sadnica <b>${v.sq?money(v.sp):'Nema na stanju'}</b></button></div></details><input type="hidden" id="kind-${v.id}"><div class="buy-controls"><label for="qty-${v.id}">Količina</label><input id="qty-${v.id}" type="number" min="1" inputmode="numeric" placeholder="Unesite količinu" disabled oninput="validateQty(this,${v.id})"></div><div class="card-actions"><button onclick="detail(${v.id})">Detalji</button><button id="add-${v.id}" class="add" onclick="addSelected(this,${v.id})" disabled>Dodaj u korpu</button></div></div></article>`}
function renderDirectory(){const q=($('#directorySearch')?.value||'').toLowerCase(),list=[...varieties].filter(v=>v.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'sr'));if($('#directoryList')){$('#directoryCount').textContent=list.length+' sorti vinove loze';$('#directoryList').innerHTML=list.map(v=>`<button onclick="detail(${v.id})"><span>${v.name.charAt(0).toUpperCase()}</span><b>${v.name}</b><i>›</i></button>`).join('')}}
function renderPrices(){const q=($('#priceSearch')?.value||'').toLowerCase(),list=[...varieties].filter(v=>v.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'sr'));if($('#priceList')){$('#priceCount').textContent=list.length+' sorti';$('#priceList').innerHTML=list.map(v=>`<button onclick="detail(${v.id})"><span class="price-name"><i>${v.name.charAt(0).toUpperCase()}</i><b>${v.name}</b></span><strong>${v.sp?money(v.sp):'—'}</strong><em>${v.cp?money(v.cp):'—'}</em></button>`).join('')}}
function render(){const q=$('#search')?.value.toLowerCase()||'',r=$('#ripen')?.value||'',c=$('#color')?.value||'',t=$('#type')?.value||'',a=$('#available')?.checked;let list=varieties.filter(v=>(!q||(v.name+' '+v.desc+' '+v.exp).toLowerCase().includes(q))&&(!r||v.ripen===r)&&(!c||v.color===c)&&(!t||v.type===t)&&(!a||v.sq||v.cq));$('#catalogGrid').innerHTML=list.map(card).join('')||'<div class="empty-card"><h3>Nema rezultata</h3><p>Promijenite pojam ili filter pretrage.</p></div>';$('#resultCount').textContent=list.length+' sorti';const featured=varieties.filter(v=>v.featured);$('#featured').innerHTML=featured.map(card).join('')||'<div class="empty-card featured-empty"><h3>Nema izdvojenih sorti</h3><p>Označite ih u admin panelu.</p></div>';renderAdmin();renderDirectory();renderPrices()}
function showPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));closeDrawer();scrollTo(0,0);if(id==='catalog')render()}
function detail(id){const v=varieties.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="detail-grid">${v.images?.length?`<div class="detail-gallery"><img class="main-photo" src="${v.images[0]}" alt="${v.name}"><div class="thumbs">${v.images.map((img,i)=>`<button onclick="this.closest('.detail-gallery').querySelector('.main-photo').src='${img}'"><img src="${img}" alt="${v.name} ${i+1}"></button>`).join('')}</div></div>`:`<div class="detail-art grape-art ${v.color==='Crna'?'dark':v.color==='Crvena'?'red':''}">🍇</div>`}<div><span class="tag">${v.ripen}</span><h1>${v.name}</h1><div class="facts"><div><small>Zemlja porijekla</small><br><b>${v.origin||'Za dopunu'}</b></div><div><small>Autor / selekcionar</small><br><b>${v.author||'Za dopunu'}</b></div><div><small>Boja</small><br><b>${v.color}</b></div><div><small>Vrijeme zrenja</small><br><b>${v.maturity||v.ripen}</b></div><div><small>Masa grozda</small><br><b>${v.clusterWeight||'Za dopunu'}</b></div><div><small>Masa bobice</small><br><b>${v.berryWeight||'Za dopunu'}</b></div><div><small>Veličina bobice</small><br><b>${v.berrySize||'Za dopunu'}</b></div><div><small>Otpornost na mraz</small><br><b>${v.frost||'Za dopunu'}</b></div><div><small>Otpornost na bolesti</small><br><b>${v.disease||'Za dopunu'}</b></div><div><small>Ukus</small><br><b>${v.taste||'Za dopunu'}</b></div></div><h3>Opis sorte</h3><p>${v.desc}</p><h3>Lično iskustvo na mom terenu</h3><p>${v.exp}</p><h3>⚠️ Nedostaci</h3><p>${v.disadvantages||'Podaci o nedostacima još nisu uneseni.'}</p><div class="detail-order"><p class="eyebrow">DODAJ U KORPU</p><h2>Naručite ovu sortu</h2><div class="detail-buy"><label>Sadnica · ${v.sp?money(v.sp):'Nema na stanju'}<span><input id="detail-sapling-${v.id}" type="number" min="1" max="${v.sq}" placeholder="Količina" ${!v.sq?'disabled':''}><button onclick="detailAdd(${v.id},'Sadnica')" ${!v.sq?'disabled':''}>+ Dodaj</button></span></label><label>Reznica · ${v.cp?money(v.cp):'Nema na stanju'}<span><input id="detail-cutting-${v.id}" type="number" min="1" max="${v.cq}" placeholder="Količina" ${!v.cq?'disabled':''}><button onclick="detailAdd(${v.id},'Reznica')" ${!v.cq?'disabled':''}>+ Dodaj</button></span></label></div></div></div></div>`;$('#modal').classList.add('open')}
function detailAdd(id,type){const v=varieties.find(x=>x.id===id),input=$('#detail-'+(type==='Sadnica'?'sapling':'cutting')+'-'+id),qty=Number(input.value),max=type==='Sadnica'?v.sq:v.cq;if(!qty||qty<1||qty>max){toast('Unesite ispravnu količinu');return}cart.push({name:v.name,type,price:type==='Sadnica'?v.sp:v.cp,qty});updateCart();toast(qty+' × '+type.toLowerCase()+' dodato u korpu')}
function chooseProduct(option,id,type){const card=option.closest('.card'),v=varieties.find(x=>x.id===id),max=type==='Sadnica'?v.sq:v.cq;if(!max)return;card.querySelector('[id^=kind-]').value=type;card.querySelector('[id^=picker-label-]').innerHTML=`${type} – ${money(type==='Sadnica'?v.sp:v.cp)} <span>⌄</span>`;card.querySelector('details').open=false;const qty=card.querySelector('[id^=qty-]');qty.disabled=false;qty.max=max;qty.value='';qty.placeholder=`Unesite količinu (najviše ${max})`;qty.focus();card.querySelector('[id^=add-]').disabled=true}
document.addEventListener('click',e=>{const option=e.target.closest('[data-product-id]');if(option&&!option.disabled)chooseProduct(option,Number(option.dataset.productId),option.dataset.productType)});
function validateQty(qtyEl,id){const card=qtyEl.closest('.card'),v=varieties.find(x=>x.id===id),type=card.querySelector('[id^=kind-]').value,max=type==='Sadnica'?v.sq:v.cq;let qty=Number(qtyEl.value);if(qty>max)qtyEl.value=max;if(qty<0)qtyEl.value='';card.querySelector('[id^=add-]').disabled=!(Number(qtyEl.value)>=1&&Number(qtyEl.value)<=max)}
function addSelected(button,id){const card=button.closest('.card'),v=varieties.find(x=>x.id===id),type=card.querySelector('[id^=kind-]').value,qty=Number(card.querySelector('[id^=qty-]').value),max=type==='Sadnica'?v.sq:v.cq;if(!type||!qty||qty>max)return;const price=type==='Sadnica'?v.sp:v.cp;cart.push({name:v.name,type,price,qty});updateCart();toast(`${qty} × ${type.toLowerCase()} dodato u korpu`)}
function updateCart(){$('#cartCount').textContent=cart.reduce((s,x)=>s+(x.qty||1),0);$('#cartItems').innerHTML=cart.map((x,i)=>`<div class="cart-item"><span><b>${x.name}</b><br><small>${x.type} · količina: ${x.qty||1}</small></span><span>${money(x.price*(x.qty||1))} <button onclick="removeCart(${i})">×</button></span></div>`).join('')||'<p>Korpa je prazna.</p>';$('#total').textContent=money(cart.reduce((s,x)=>s+Number(x.price)*(x.qty||1),0))}function removeCart(i){cart.splice(i,1);updateCart()}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function openCheckout(){if(!cart.length){toast('Korpa je prazna');return}const subtotal=cart.reduce((s,x)=>s+x.price*(x.qty||1),0),shipping=12;$('#modalContent').innerHTML=`<h1>Završetak narudžbe</h1><div class="order-summary">${cart.map(x=>`<div><span>${x.name} · ${x.type} × ${x.qty}</span><b>${money(x.price*x.qty)}</b></div>`).join('')}<div><span>Poštarina</span><b>${money(shipping)}</b></div><div class="grand"><b>Ukupno</b><b>${money(subtotal+shipping)}</b></div></div><form class="checkout-form" onsubmit="prepareOrder(event)"><div class="two"><label>Ime *<input name="ime" required></label><label>Prezime *<input name="prezime" required></label></div><label>Broj telefona *<input name="telefon" type="tel" required></label><label>Grad *<input name="grad" required></label><button class="primary" type="submit">Potvrdi narudžbu</button></form>`;$('#cart').classList.remove('open');$('#overlay').classList.remove('open');$('#modal').classList.add('open')}
function prepareOrder(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);$('#modalContent').innerHTML=`<div class="empty-card"><div>✓</div><h3>Narudžba je pripremljena</h3><p>${data.ime} ${data.prezime}, ${data.grad}<br>${data.telefon}</p><p>Ukupno sa poštarinom: <b>${money(subtotal+12)}</b></p><p>Automatsko slanje PDF-a na vinogradfoca@gmail.com povezaćemo u završnoj fazi.</p></div>`}
function renderAdmin(){if(!$('#adminList'))return;$('#adminList').innerHTML=varieties.map(v=>`<div class="admin-row"><span><b>${v.name}</b>${v.featured?'<i class="featured-badge">Izdvojena</i>':''}<br><small>${v.ripen} · sadnica ${v.sq}, reznica ${v.cq}</small></span><span><button onclick="editVar(${v.id})">Uredi</button><button onclick="deleteVar(${v.id})">Obriši</button></span></div>`).join('')}
function renderAdminImages(){const box=$('#adminImagePreview');if(!box)return;box.innerHTML=pendingImages.map((img,i)=>`<figure><img src="${img}" alt="Slika ${i+1}"><button type="button" onclick="removeAdminImage(${i})" aria-label="Obriši sliku">×</button><figcaption>${i===0?'Glavna slika':'Slika '+(i+1)}</figcaption></figure>`).join('')}
function removeAdminImage(i){pendingImages.splice(i,1);renderAdminImages()}
function editVar(id){const v=varieties.find(x=>x.id===id);for(const [f,k] of [['editId','id'],['name','name'],['aRipen','ripen'],['aColor','color'],['aType','type'],['saplingPrice','sp'],['saplingQty','sq'],['cuttingPrice','cp'],['cuttingQty','cq'],['description','desc'],['experience','exp'],['disadvantages','disadvantages']])$('#'+f).value=v[k]||'';pendingImages=[...(v.images||[])].slice(0,3);renderAdminImages();$('#aFeatured').checked=Boolean(v.featured);scrollTo({top:0,behavior:'smooth'})}function deleteVar(id){if(confirm('Da li sigurno želite obrisati cijelu sortu? Ova radnja briše i njene slike iz kataloga.')){varieties=varieties.filter(x=>x.id!==id);save();render()}}
$('#imageUpload').addEventListener('change',e=>{const files=[...e.target.files];if(pendingImages.length+files.length>3){toast('Dozvoljene su najviše 3 slike po sorti');e.target.value='';return}files.forEach(file=>{const reader=new FileReader();reader.onload=()=>{pendingImages.push(reader.result);renderAdminImages()};reader.readAsDataURL(file)});e.target.value=''});
$('#varietyForm').addEventListener('submit',e=>{e.preventDefault();const id=Number($('#editId').value)||Date.now(),old=varieties.find(x=>x.id===id),v={...old,id,name:$('#name').value,ripen:$('#aRipen').value,color:$('#aColor').value,type:$('#aType').value,featured:$('#aFeatured').checked,sp:Number($('#saplingPrice').value),sq:Number($('#saplingQty').value),cp:Number($('#cuttingPrice').value),cq:Number($('#cuttingQty').value),desc:$('#description').value,exp:$('#experience').value,disadvantages:$('#disadvantages').value,images:[...pendingImages].slice(0,3)};const i=varieties.findIndex(x=>x.id===id);i>=0?varieties[i]=v:varieties.push(v);save();e.target.reset();$('#editId').value='';pendingImages=[];renderAdminImages();render();toast('Sorta je sačuvana')});
function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('open')}$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#overlay').classList.add('open')};$('#closeMenu').onclick=$('#overlay').onclick=closeDrawer;$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-filter]').forEach(b=>b.onclick=()=>{showPage('catalog');$('#color').value=b.dataset.filter;render()});$$('[data-type]').forEach(b=>b.onclick=()=>{showPage('catalog');$('#type').value=b.dataset.type;render()});$$('[data-ripen]').forEach(b=>b.onclick=()=>{showPage('catalog');$('#ripen').value=b.dataset.ripen;render()});$('#directorySearch').addEventListener('input',renderDirectory);$('#priceSearch').addEventListener('input',renderPrices);['search','ripen','color','type','available'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};$('#cartBtn').onclick=()=>{$('#cart').classList.add('open');$('#overlay').classList.add('open')};$('#cartClose').onclick=()=>{$('#cart').classList.remove('open');$('#overlay').classList.remove('open')};$('.cart .wide').textContent='Završi narudžbu';$('.cart .wide').onclick=openCheckout;render();updateCart();
